name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
        nim-version:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v3
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ matrix.nim-version }}

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ matrix.nim-version }}-${{ hashFiles('nasher.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-${{ matrix.nim-version }}

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Install dependencies
        run: nimble install -y --depsOnly

      - name: Build package
        run: nimble build
