name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest
        nim-version:
          - '2.0.x'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('nasher.nimble') }}
          restore-keys: |
            ${{ runner.os }}-nimble-

      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v2
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: nimble install -y --depsOnly

      - name: Run Nimble tests
        run: nimble test -y

      - name: Build package
        run: nimble build
